//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlLiteTrial
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRoleTaker
    {
        public int RoleTakerID { get; set; }
        public int MeetingID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public int RoleBookingTypeID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual MeetingRole MeetingRole { get; set; }
        public virtual RoleBookingType RoleBookingType { get; set; }
        public virtual User User { get; set; }
    }
}
