//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlLiteTrial
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectEventLog
    {
        public int ObjectEventLogID { get; set; }
        public int ObjectTypeID { get; set; }
        public int ObjectID { get; set; }
        public int EventTypeID { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual ObjectType ObjectType { get; set; }
    }
}
