//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlLiteTrial
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleBookingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleBookingType()
        {
            this.MeetingRoleTakers = new HashSet<MeetingRoleTaker>();
        }
    
        public int RoleBookingTypeID { get; set; }
        public string RoleBookingTypeName { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingRoleTaker> MeetingRoleTakers { get; set; }
    }
}
